package dev.stashy.extrasounds.mapping;

import net.minecraft.item.Item;
import org.jetbrains.annotations.NotNull;

import java.util.function.Function;

/**
 * The generator API that provides your item sounds.
 */
public final class SoundGenerator {
    public final Function<Item, SoundDefinition> itemSoundGenerator;

    private SoundGenerator(Function<Item, SoundDefinition> itemSoundGenerator) {
        this.itemSoundGenerator = itemSoundGenerator;
    }

    /**
     * Tells the sounds of your items and/or blocks to ExtraSounds.<br>
     * The {@code id} you define in {@code fabric.mod.json} must match the target item's namespace.
     * <hr/>
     * <p>✔ This will work:</p>
     * <ul>
     *     <li><code>fabric.mod.json</code><br>
     *     <pre>id: "extrasounds"</pre></li>
     *     <li>Item registration<br>
     *     <pre>Registry.register(Registries.ITEM, Identifier.of("extrasounds", "newitem"), new Item(...));</pre></li>
     *     <li>Sound generator<br>
     *     <pre>public static final SoundGenerator GENERATOR = SoundGenerator.of(item -> {...});</pre></li>
     * </ul>
     * <h5>✘ This will not work:</h5>
     * <ul>
     *     <li><code>fabric.mod.json</code><br>
     *     <pre>id: "extrasounds"</pre></li>
     *     <li>Item registration<br>
     *     <pre>Registry.register(Registries.ITEM, Identifier.of("extra-sounds", "newitem"), new Item(...));</pre>
     *     -> Reason: namespace of Identifier does not match your mod id. ("extrasounds" vs. "extra-sounds")</li>
     *     <li>Sound generator<br>
     *     <pre>public static final SoundGenerator GENERATOR = SoundGenerator.of(item -> {...});</pre></li>
     * </ul>
     *
     * @param itemSoundGenerator The instance of a {@link Function} that converts from {@link Item} to {@link SoundDefinition}.
     * @see <a href="https://github.com/lonefelidae16/extra-sounds/wiki/Custom-sounds-for-mod-developers#defining-autogenerated-sounds">GitHub wiki - Defining autogenerated sounds</a>
     */
    public static SoundGenerator of(@NotNull Function<Item, SoundDefinition> itemSoundGenerator) {
        return new SoundGenerator(itemSoundGenerator);
    }

    /**
     * <h5>Deprecated</h5>
     * Parameter {@code namespace} is no longer required.
     * Use {@link SoundGenerator#of(Function)} instead.
     *
     * @see SoundGenerator#of(Function)
     */
    @Deprecated
    public static SoundGenerator of(@NotNull String namespace, @NotNull Function<Item, SoundDefinition> itemSoundGenerator) {
        return new SoundGenerator(itemSoundGenerator);
    }

    /**
     * <h5>Deprecated</h5>
     * Parameter {@code namespace} and {@code modId} are no longer required.
     * Use {@link SoundGenerator#of(Function)} instead.
     *
     * @see SoundGenerator#of(Function)
     */
    @Deprecated
    public static SoundGenerator of(@NotNull String namespace, @NotNull String modId, @NotNull Function<Item, SoundDefinition> itemSoundGenerator) {
        return new SoundGenerator(itemSoundGenerator);
    }
}
