name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Your time is a valuable first step for our developers to solve a problem.

  - type: textarea
    attributes:
      label: Environment info
      description: |
        Please list what Minecraft version and mods you are using.
      placeholder: |
        - Minecraft version, ExtraSounds version you are using.
        - Fabric API or Quilted Fabric API version.
        - Other mods and their versions.
        - optional: Operating system you are using and Java version (e.g. "Windows 10 with Bundled JRE", "Ubuntu 22.04 with OpenJDK 17.0.8+7-Ubuntu-122.04", etc.)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Please write a brief description of the bug, including what you expect to happen and what is currently happening.
      placeholder: |
        Feature '...' is not working properly. I expect '...' to happen, but '...' happens instead.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Step-by-step reproduction instructions
      description: Please write the steps needed to reproduce the bug.
      placeholder: |
        1. Launch the game with '...'
        2. Open '...' / Interact to '...'
        3. Click on '...'
    validations:
      required: true

  - type: dropdown
    id: compatibility
    attributes:
      label: Is this related to other mods or libraries?
      multiple: true
      options:
        - 'Yes'
        - 'No'
        - 'Not sure'
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots, latest.log, code snippet
      description: |
        If possible, please upload a screenshot or screen recording which demonstrates the bug. You can use LICEcap to create a GIF screen recording: https://www.cockos.com/licecap/
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
        If you have already tracked down the cause of this bug, please share the permalink of the line (e.g. https://github.com/lonefelidae16/extra-sounds/blob/a8911ab086458699bf46a4d46ce0b85c7f228a34/src/main/java/dev/stashy/extrasounds/ExtraSounds.java#L24-L30 )
        For small snippets paste it directly here, or you can use GitHub Gist to share multiple code files: https://gist.github.com
    validations:
      required: false

#  - type: dropdown
#    id: existing
#    attributes:
#      label: Please confirm that you have searched existing issues in the repo.
#      description: You can do this by searching https://github.com/lonefelidae16/extra-sounds/issues
#      multiple: true
#      options:
#        - 'Yes'
#        - 'No'
#    validations:
#      required: true
#
